### PR TITLE
Matter 1.4 upmerge

### PR DESCRIPTION
**Pull request by adigie**
* Merged upstream `master` up to project-chip/connectedhomeip@78f489d7d5cb5f8c48120d8a18e14efb8fe01d11
* Cherry-picked changes from `v1.4-branch` up to project-chip/connectedhomeip@96eab2936a965edb4a8499ca0f401831279bfb64

### CODE REVIEW

**Review by kkasperczyk-no — COMMENTED** [review]
LGTM overall! But there is one unfortunate thing... New commit was merged on top of sdk-connectedhomeip in the meantime: https://github.com/nrfconnect/sdk-connectedhomeip/commit/93c712e6e0be9211507cb9e559860b32daa984ed and it's necessary to somehow rebase your PR to get this new commit on top.

**Review by maciejbaczmanski — COMMENTED** [review]
I think that "[nrf noup] Mark CHIP_ICD_LIT_SUPPORT experimental" (https://github.com/nrfconnect/sdk-connectedhomeip/pull/512/commits/15dc937d8b90694e0df063c2e6eaccb7da050fda) could be dropped as we will support it ithanks to this upmerge, right @kkasperczyk-no ?

**Comment by kkasperczyk-no** [comment]
> I think that "[nrf noup] Mark CHIP_ICD_LIT_SUPPORT experimental" ([15dc937](https://github.com/nrfconnect/sdk-connectedhomeip/commit/15dc937d8b90694e0df063c2e6eaccb7da050fda)) could be dropped as we will support it ithanks to this upmerge, right @kkasperczyk-no ?

Yes, sure.

**Comment by adigie** [comment]
Rebased, fixed docs build and dropped 15dc937d8b90694e0df063c2e6eaccb7da050fda.

**Review by maciejbaczmanski — APPROVED** [review]

**Comment by kkasperczyk-no** [comment]
> Rebased, fixed docs build and dropped [15dc937](https://github.com/nrfconnect/sdk-connectedhomeip/commit/15dc937d8b90694e0df063c2e6eaccb7da050fda).

@adigie I meant that you are missing this commit from the master branch: `[nrf noup] config: Add support for non-PM factory data generation`. I don't know how rebase went through, but I still can't see it in the tree.

**Review by kkasperczyk-no — APPROVED** [review]

**Review by ArekBalysNordic — APPROVED** [review]

**Pull request merged**
