### PR TITLE
Fix build latest wifi

### PR DESCRIPTION
**Pull request by krish2718**
Fix the build breakage with latest Wi-Fi driver PR: https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-8495/7/testReport/

### CODE REVIEW

**Comment by markaj-nordic** [comment]
@krish2718 could you please link the PR/PRs which needs to be merged before we can merge this one? I assume:
- sdk-hostap:
https://github.com/nrfconnect/sdk-hostap/pull/14
- sdk-nrf:
- https://github.com/nrfconnect/sdk-nrf/pull/8495

**Comment by krish2718** [comment]
> @krish2718 could you please link the PR/PRs which needs to be merged before we can merge this one? I assume:
> 
> * sdk-hostap:
>   [Merge dev branch sdk-hostap#14](https://github.com/nrfconnect/sdk-hostap/pull/14)
> * sdk-nrf:
> * [Wi-Fi: Merge dev branch sdk-nrf#8495](https://github.com/nrfconnect/sdk-nrf/pull/8495)

Yes, https://github.com/nrfconnect/sdk-nrf/pull/8495 (this already includes the sdk-hostap manifest update).

**Comment by krish2718** [comment]
also the Darwin related CI failures doesn't seem to be Wi-Fi related, can we ignore those?

**Comment by markaj-nordic** [comment]
> also the Darwin related CI failures doesn't seem to be Wi-Fi related, can we ignore those?

I hope so, I faced the same with my latest PR, also not related to Darwin. Let's see what's other's thoughts on that.

**Comment by krish2718** [comment]
Also, this is a circular dependency, for the `sdk-nrf` CI to be passed, this needs to be merged, and for matter to build once this is merged it needs latest driver, so, once that is reviewed before merging

* merge this
* update manifest PR->Commit
* merge sdk-nrf.

**Comment by kkasperczyk-no** [comment]
> Also, this is a circular dependency, for the sdk-nrf CI to be passed, this needs to be merged
@krish2718 why? I think what needs to happen is:
1. CI is green on you sdk-nrf PR with this open PR referenced in west.yml, so we can be sure this PR was validated vs sdk-nrf change.
2. Then we can merge this PR and you need to switch pull/<pr_number/head in your sdk-nrf PR to the commit SHA we got after merging this PR.
3. CI is validated once again on sdk-nrf PR.

I don't see circular dependency here. If we will merge this PR to sdk-connectedhomeip master it will not work vs sdk-nrf master, because there will not be your Wi-Fi driver change there yet. However we don't recommend using sdk-nrf master with sdk-connectedhomeip master, but sdk-nrf master with specific revision of sdk-connectedhomeip, so I would say everything should be fine.

**Comment by krish2718** [comment]
> > Also, this is a circular dependency, for the sdk-nrf CI to be passed, this needs to be merged
> 
> @krish2718 why? I think what needs to happen is:
> 
> 1. CI is green on you sdk-nrf PR with this open PR referenced in west.yml, so we can be sure this PR was validated vs sdk-nrf change.
> 2. Then we can merge this PR and you need to switch pull/<pr_number/head in your sdk-nrf PR to the commit SHA we got after merging this PR.
> 3. CI is validated once again on sdk-nrf PR.

These are the same steps I was referring to.

> I don't see circular dependency here. If we will merge this PR to sdk-connectedhomeip master it will not work vs sdk-nrf master, because there will not be your Wi-Fi driver change there yet. However we don't recommend using sdk-nrf master with sdk-connectedhomeip master, but sdk-nrf master with specific revision of sdk-connectedhomeip, so I would say everything should be fine.

Yes, its only a problem if we use `master` of `sdk-connectedhomeip`.

**Comment by kkasperczyk-no** [comment]
> These are the same steps I was referring to.

Ok then, I misunderstood something and thought you would like to merge this PR before passing Ci on sdk-nrf.

**Comment by krish2718** [comment]
> > These are the same steps I was referring to.
> 
> Ok then, I misunderstood something and thought you would like to merge this PR before passing Ci on sdk-nrf.

I was suggesting that in case we want to get both `master` working together, I guess we can leave that now.

**Review by Damian-Nordic — APPROVED** [review]

**Comment by krish2718** [comment]
CI passing now, we can merge this https://github.com/nrfconnect/sdk-nrf/pull/8495

**Review by markaj-nordic — APPROVED** [review]

**Pull request merged**
