### PR TITLE
[nrf mergeup] Merge upstream to the bbd19d9 commit

### PR DESCRIPTION
**Pull request by kkasperczyk-no**
Merged upstream commits on November 15th

### CODE REVIEW

**Comment by kkasperczyk-no** [comment]
@Damian-Nordic I found two old `[no up]` commits (https://github.com/nrfconnect/sdk-connectedhomeip/commit/a68983a302979eaf59d5ca75006a1fc8b471df12 and https://github.com/nrfconnect/sdk-connectedhomeip/commit/a523f2f88a9c51c9503ea4854a2f41a84f861cef) that needed to be reverted to avoid conflicts. It seems to me that they are not longer needed, as it is already on master in similar form, but could you verify it?

**Comment by Damian-Nordic** [comment]
@kkasperczyk-no yes, they should be reverted.

**Comment by Damian-Nordic** [comment]
@kkasperczyk-no Could you also change the recommended ncs version to `origin/main` like in https://github.com/nrfconnect/sdk-connectedhomeip/pull/36?

**Comment by kkasperczyk-no** [comment]
> @kkasperczyk-no Could you also change the recommended ncs version to `origin/main` like in #36?

Ah yes, it's fixed

**Review by LuDuda — APPROVED** [review]

**Review by Damian-Nordic — APPROVED** [review]

**Pull request merged**
