### PR TITLE
[nrf noup] Fix build for 7001 Emulation

### PR DESCRIPTION
**Pull request by krish2718**
Add support for nRF7001DK, this was missed earlier, but now we have customers that need 2.4GHz only Wi-Fi using this.

### CODE REVIEW

**Review by Damian-Nordic — APPROVED** [review]

**Comment by ArekBalysNordic** [comment]
Failures are not connected to this PR.

**Review by ArekBalysNordic — APPROVED** [review]

**Comment by krish2718** [comment]
> Failures are not related to this PR.

I just triggered a re-run, should I rebase too?

**Comment by ArekBalysNordic** [comment]
> > Failures are not related to this PR.
> 
> I just triggered a re-run, should I rebase too?

I guess, you rebased to main instead of v2.5-branch and you pulled too many commits :)

**Comment by krish2718** [comment]
> > > Failures are not related to this PR.
> > 
> > 
> > I just triggered a re-run, should I rebase too?
> 
> I guess, you rebased to main instead of v2.5-branch and you pulled too many commits :)

Fixed this but no luck. How should we proceed with these failures?

**Pull request merged**
